export type { IGetProps } from './error'
export type { IPageHome } from './home-page'
export type { IPagePokemon, IPokemon } from './pokemon-page'
export type { IGetPokemon, IGetPokemons } from './pokemon'
export type { IDetailsPokemon } from './details-pokemon'
export type { ICardPokemon } from './card-pokemon'
export type { IInfoPokemon } from './info-pokemon'
export type { IPokemonText } from './pokemon-text'
export type { IPokemonImages } from './pokemon-images'
export type { IPokemonName } from './pokemon-name'
export type { ISeo } from './seo'
export type { IGetPathsProps } from './get-paths-props'
export type { IHeart } from './heart'
