export { Title } from './title'
export { Links } from './links'
export { PokemonText } from './pokemon-text'
export { PokemonImages } from './pokemon-images'
export { PokemonName } from './pokemon-name'
export { Heart } from './heart'
